apiVersion: v1
kind: Service
metadata:
  name: api-inferencia
  namespace: default
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
    nodePort: 32001
  selector:
    app: api-inferencia
  sessionAffinity: None
  type: NodePort
