apiVersion: v1
kind: Service
metadata:
  name: api-update
  namespace: default
spec:
  ports:
  - port: 5002
    protocol: TCP
    targetPort: 5002
    nodePort: 32002
  selector:
    app: api-update
  type: NodePort
status:
  loadBalancer: {}
